# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: LibreWorkingTimes
description: >- # this means to ignore newlines until "baseurl:"
  LibreWorkingTimes is progressive web app (PWA) to easily mange working times.
baseurl: "" # the subpath of your site, e.g. /blog
domain: libreworkingtimes.wiegandt.eu
url: "https://libreworkingtimes.wiegandt.eu" # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: Nicklas Wiegandt
  email: nicklas+libreworkingtimes@wiegandt.eu
  twitter: nicklas2751
social:
  name: Hydra Template
  links:
    - https://github.com/CloudCannon/hydra-jekyll-template

# Build settings
remote_theme: CloudCannon/hydra-jekyll-template

timezone: Europe/Berlin

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  - scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "index.html"
    values:
      layout: "default"


jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_select_data:
  social_icons:
    - Twitter
    - GitHub